---
title: "DIY Solar Aquaponics"
author: "Jeffrey Long"
format: html
editor: visual
---

## DIY Aquaponics

Starting from a fantastic aquaponics video on YouTube, <https://youtu.be/HTq364RwH44?si=uOUxhjAsewHC32uz>

Here are some notes to build a system.

#### Notes from the YouTube Video

Jerry Coleby-Williams visits environmental scientist Kieran Richardt in an industrial estate to see his teaching space, which includes an aquaponic green wall.

The self-contained recirculating system contains fish in a reservoir at its base, so the green wall is watered with fertiliser-rich fish waste. It shows ways of tying terrestrial and aquatic environments.

Grow lamps are used to give the plants UV light and perennial plants such as flamingo flower (Anthurium ‘Pure Red Queen’), rasp fern (Doodia aspera), kangaroo fern (Phlebodium aureum syn. Polypodium aureum), maidenhair fern (Adiantum raddianum), crested fern (Pleopeltis fallax syn. Polypodium fallax), and pitcher plants (Nepenthes maxima x ventricosa) are used to create the living wall.

To create your own green wall, budget for about \$500 worth of materials; you’ll need to be able to use some basic tools and have a few hours spare – the perfect weekend project.

### You’ll Need

-   Bitumastic cement paint (like you would use behind tiles in a bathroom) if you don’t have a water proof wall

-   Reservoir pond – either a plastic container or a wooden trough (we used recycled treated timber) lined with pond lining

<!-- -->

-   Frame – to support the growing wall. Metal lasts longer, but you could use wood – such as a recycled door frame

-   Expanded PVC foam sheet and a cover, such as recycled PET felt, which has lots of surface area for the growth of (good) bacteria

-   19mm irrigation pipe (long enough to exten along the top and down one side) plus a stopper, an elbow and 4mm drippers – enough to place one 20mm apart along its top length

<!-- -->

-   Stanley knife, screws, drill, measuring tape

-   Plants such as ferns, orchids, flamingo flowers, pitcher plants and other epiphytes

-   Fish

    ### Method

-   If necessary, paint your wall with bitumastic paint

-   Make the wooden trough. We predrilled the holes then connected the timber using baton screws

-   Line with either pond liner or a few layers of builder’s plastic

-   Fix the liner into place using some timber batons, screwed into place

-   Trim off excess plastic

-   Construct a frame to support your wall. We used a recycled aluminium gate frame as the back of the wall.

-   Bolt on your waterproof board (e.g. expanded PVC foam) to the frame

-   Staple your felt to the front of the board, keeping it tight but allowing space to fit the dripper pipe at the top end. Do not wrap excess fabric around the back until the dripper pipe is in place, but trim the excess from the corners to make it easier to wrap around later.

-   Fit a stopper to one end of the 10mm pipe, and the elbow at the other end. Now pierce holes to place 4mm drippers every 20cm along the pipe.

-   Place the pipe under the fabric at the top of the board and staple it in place by folding over the excess fabric.

-   Fix the frame into the pond, wrapping the legs in more felt to stop any sharp edges from piercing the plastic

-   Mark crosses every 10-15cm on the front of the felt where you would like the plants to go, then cut with a Stanley knife.

-   Remove the excess soil from your plants, poke them into the holes in the felt and staple them into place

-   Add your fish to the reservoir - make sure the water is room temperature and that the water has been pH balanced first.

    ## Other Tips

-   Make sure the area has a strong enough structure to support your wall and choose plants that suit the position. i.e. indoor plants for an indoor position, sun-loving plants for outside etc. The walls work equally well without fish, but to make it a complete aquaponics system, you need fish. A traditional aquaponics set would have fish for eating, however ornamental fish work just as well. If you have fish, don’t forget to feed them, and if you don’t have fish, don’t forget to feed the plants using liquid fertiliser. Top up the water as necessary and partially change the water regularly.
